### ISSUE TITLE
Adding dismiss button to each notification card

### ISSUE THREAD

**Issue by adiic** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#1]
@RonnyWeiss, Is it quick to add dismiss button for each card? 
Can it generate an event when card is dismissed?

**Comment by RonnyWeiss** [comment]
Hello

It’s not supported by default but I made you an example in my example App:

https://apex.oracle.com/pls/apex/f?p=103428:2

how it can work. You can download the app or download an update of the Plugin with the new example in SQL examples.

I will checkin the update tomorrow morning.

Here is the sample SQL Statement (You have to disable Escape Special characters and Keep in mind that you have to Prevent xss then in sql:

SELECT /* sets the icon of the list item */
    'fa-exclamation-triangle' AS NOTE_ICON, 
    /* sets the color of the list icon */
    'rgb(192,0,15)' AS NOTE_ICON_COLOR, 
    /* sets the title of the list item (html possible) */
    'Alarm occurred' AS NOTE_HEADER, 
    /* sets the text of the list item (html possible */
    'There''s an alarm in <b>Station 3</b>. Error code is <b style="color:rgba(192,0,15);">#304-AD. </b><br><br>' ||
    '<button class="t-Button t-Button--icon t-Button--success t-Button--iconRight" onclick="$(''body'').trigger(''event-fired'');console.log(''event-fired'')" '|| 
    'type="button"><span class="t-Icon t-Icon--left fa fa-check" aria-hidden="true"></span><span class="t-Button-label">Fire Event</span>' ||
    '<span class="t-Icon t-Icon--right fa fa-check" aria-hidden="true"></span></button>' AS NOTE_TEXT, 
    /* set the link when click on list item */
    NULL AS NOTE_LINK, 
    /* sets the color of the left box shadow */
    'rgb(192,0,15)' AS NOTE_COLOR
FROM
    DUAL

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
Hello

Please take a look at release 1.4. The accept or decline feature is now available.

Have fun with the plug-in

Kind regards

Ronny
