### ISSUE TITLE
hideOnRefresh is not so valid

### ISSUE THREAD

**Issue by gomanuke** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#10]
> ideOnRefresh(boolean)Set if Notification menu should hide on Refresh. Note, when you disable this feature then the **notification menu does not hide when click on area outside of the notification menu**

No, it hides after click outside even when 
{
    "refresh": 0,
    "mainIcon": "fa-bell",
    "mainIconColor": "white",
    "mainIconBackgroundColor": "rgba(70,70,70,0.9)",
    "mainIconBlinking": true,
    "counterBackgroundColor": "rgb(232, 55, 55 )",
    "counterFontColor": "white",
    "linkTargetBlank": false,
    "showAlways": false,
    "browserNotifications": {
        "enabled": false,
        "cutBodyTextAfter": 100,
        "link": false
    },
    "accept": {
        "color": "#44e55c",
        "icon": "fa-check"
    },
    "decline": {
        "color": "#b73a21",
        "icon": "fa-close"
    },
    **"hideOnRefresh": false**
}

**Comment by RonnyWeiss** [comment]
Thank you. I have changed documentation in version 1.6.2
