### ISSUE TITLE
Touch Problem

### ISSUE THREAD

**Issue by walterpais81** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#12]
Im trying your notifications and i have trouble on touch devices like smartphone or tablets, when tapping the notification bell it open and close inmediatly. 
I've chage the js, when you use "touchstart" i must use "touch" so the event fires ok.

**Comment by RonnyWeiss** [comment]
Hello Thank you for the issue. I have fixed the issue in Version 1.6.4. Hope you'll have fun with the plugin
