### ISSUE TITLE
behavior change if device is mobile

### ISSUE THREAD

**Issue by ahmad-fathy-1981** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#15]
while trying click on Notification-Menu and responsive is ( 400*578 ) as mobile 
the popup menu not displayed except the cursor ( Press + Hold ) 
this is different behavior if we opening by normal responsive like desktop
![1](https://user-images.githubusercontent.com/57535548/111118099-69f2f800-8579-11eb-86f9-d681b8762405.jpg)
![2](https://user-images.githubusercontent.com/57535548/111118106-6c555200-8579-11eb-9702-de0b354949bd.jpg)

**Comment by RonnyWeiss** [comment]
Hello

Thank you for issue, but I don't understand the problem. I tested it on my android phone and click on the menu is working fine. So I don't need to hold? 

Kind regards

Ronny

**Comment by ahmad-fathy-1981** [comment]
Hi , good day

Thank you for your time but that exactly happen with me . When trying click by mobile find me must be press and hold

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by walterpais81** [comment]
Wich pluggin version are you using? In an older version there was an issue [https://github.com/RonnyWeiss/Apex-Notification-Menu-for-NavBar/issues/12]

**Comment by ahmad-fathy-1981** [comment]
thank you . I indeed found the issue resolved in later version thank you
