### ISSUE TITLE
notification stays open on click

### ISSUE THREAD

**Issue by xCite1986** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#2]
i add a modal dialog window linked to the notification, on click the notification menu stays open and in foreground.
is it possible to close them on click?

![2018-01-03_12-55-00](https://user-images.githubusercontent.com/10913090/34519725-bc43ff64-f085-11e7-9985-fffaf97d64ef.png)

**Comment by RonnyWeiss** [comment]
Hello

I add support for mo0dal dialogs. Hope that helps.

Kind regards

Ronny
