### ISSUE TITLE
Refresh after Accept / Decline

### ISSUE THREAD

**Issue by hairpin666** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#2]
Hi Ronny,

First of all thank you so much for this amazing plugin it really leverages our Oracle Apex application.

One simple question or improvement suggestion.

After a user pressed accept / decline, can we refresh / redraw the notification area? 
We use it to list reminder / todos for the user and with a "mute" button he can mute the notification. It would be nice that this notification disappears from the notification menu instantly.

Is there an easy workaround?

Thanks / Danke

**Comment by RonnyWeiss** [comment]
Hello

Thank you for your great feedback! I will implement this. At first it would help you to fire refresh event on the plugin id after you aceept or decline logic. Hope this helps ?

Kind regards Ronny

**Comment by RonnyWeiss** [comment]
Hello

I'm sorry but I forgot that accept or decline is just a link so it's impossible for me to add support for refresh after link because I do not know when your action e.g. AJAX Call to DB with PL/SQL is finished so you have to trigger refresh event manually after your action. Hope that helps you? 

Kind regards Ronny

**Comment by hairpin666** [comment]
Will give it a try, thanks

**Comment by hairpin666** [comment]
Works perfecttly: 
Just execute $("#notification-menu").trigger('apexrefresh'); and it will refresh.

**Comment by emohdaziz** [comment]
> Works perfecttly:
> Just execute $("#notification-menu").trigger('apexrefresh'); and it will refresh.

Where to execute this JavaScript expression?

**Comment by walterpais81** [comment]
i put it in a dynamic acction, the same that excetute de acept or decline action. and update de data base.

**Comment by arunprasad2** [comment]
> i put it in a dynamic acction, the same that excetute de acept or decline action. and update de data base.

Please let me show the exact place ,because I am also struck this..Thank you!!

**Comment by walterpais81** [comment]
My notification fires a dynamic action :
javascript:apex.event.trigger(document,''accionarNotificacion'',[{idaccion:"acept",idnotificacion:123123}]);void(0); as NOTE_ACCEPT link

And in the custom dynamic action i have:
- confirm action
- js code : apex.item( "P0_IDACCION" ).setValue( this.data.idaccion); apex.item( "P0_IDNOTIFICACION" ).setValue( this.data.idnotificacion);
- pl code to update database using P0 items
- js code: $("#notification-menu").trigger('apexrefresh');
