### ISSUE TITLE
Information required on how to use this plug in

### ISSUE THREAD

**Issue by sejal27** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#3]
I want to use this plugin for my application, so I downloaded and imported it. But I am not sure of the required configuration for using this in any application. Can you please provide any documentation for the same?

**Comment by RonnyWeiss** [comment]
Hello

That's very easy just add it a dynamic action to your apex page with e.g. "On Page Load" as Trigger. Then use a True-Action the Plug-in. The rest is set as example by default, so just start the appliaction and look into the Navigation Bar.

Hope that helps. I will also write this to the read me file.

Kind regards

Ronny

**Comment by RonnyWeiss** [comment]
Can I close the issue?
