### ISSUE TITLE
Icon size is not display correctly in Oracle APEX

### ISSUE THREAD

**Issue by mathiasmaciel97** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#3]
First of all thanks for contributing this kind of plugin. Following I attached you to picture to show how it's displayed. The background circle is littler regard the icon that is much bigger.
I asked myself if there is a way to **customize** this icon size like the _icon blinking_ property?

![01](https://user-images.githubusercontent.com/39440207/56080640-8d332c80-5dd1-11e9-8961-63811e7179ac.png)

**Comment by RonnyWeiss** [comment]
Hello Yes that's a problem in older Version of APEX, so please add CSS of Universal 1.0 Theme CSS.txt to your theme for perfect fit.

kind regards

Ronny

**Comment by mathiasmaciel97** [comment]
So... could you help to add CSS and customize it?
