### ISSUE TITLE
Bug if hideOnRefresh = true

### ISSUE THREAD

**Issue by Ennio71** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#4]
Hi,
thanks for your work.
I think I've found and fixed a minor bug on refresh.
If you have the list of notification opened, hideOnRefresh = true and timer fires the onClick behaviour on te bell is inverted.
I've modified script.js at line 356 from
```
 if ($(toggleNote).attr("toggled") == "false" && configJSON.hideOnRefresh) {
			ul.toggle();
 }
```
to 
```
 if ($(toggleNote).attr("toggled") == "false" && configJSON.hideOnRefresh) {
       $(toggleNote).attr("toggled", "true");
	ul.toggle();
   }
```
and seem's working.
Let'me know if I'm right.

**Comment by RonnyWeiss** [comment]
Hey thank you for your help but I thought that this code lines needed a rework! I'll fixed this bug with that rework! So thank you and please send me a message if new version has any errors!
