### ISSUE TITLE
Not a bug. Just a question - How to trigger a change when accepted/declined?

### ISSUE THREAD

**Issue by GasparYYC** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#5]
Hello @RonnyWeiss 
Thank you for this (and all other amazing plugins!)
About this one.. I have a question, I hope you don't mind.
How would you interact with a table change based on the acceptance/decline of the Notifications?

I mean, a table change  because its reading the notification from a table. I see there is the popup for declined/accepted but ideally the user should be able to acknowledge the notification so its not shown anymore.

At this point I'm looking for ideas or pointers.. I sincerely don't know what to do or what to call to start a database change based on the user input as Accept/Decline.

Thank you

**Comment by Ennio71** [comment]
I've done this way:

- Put an hidden item in your page 0 ( or where you need). For me the name is `P0_MESSAGE_ID` and contains the key for the record to update
- On the item create a dynamic action for the event `change` and type `Execute PL/SQL code`
- In the initialization of the plugin put this in the SELECT (example for DECLINE clicked)): `'javascript:apex.item("P0_MESSAGE_ID").setValue('||mes_id_messaggio||');'AS NOTE_DECLINE`


Hope this helps

**Comment by GasparYYC** [comment]
@Ennio71 Excellent idea.. I had been thinking how to activate something or set something.. Thank you!

**Comment by walterpais81** [comment]
Im ussing dynamic action that is fired by de note_declice link in the query for the notifications:
 'javascript:apex.event.trigger(document,''accionarNotificacion'',[{idaction:'||1||',idnotificacion:'||n.idnotificacion||'}]);void(0);' else null end AS NOTE_ACCEPT
