### ISSUE TITLE
Other theme

### ISSUE THREAD

**Issue by OliverTr54** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#6]
Is there any chance to integrate your plugin into the Material APEX theme? I changed the selector from `li.addClass("t-NavigationBar-item");` to a different one, but it stays empty the `<li>` is added correctly, but the dom is not changed afterwards.

Thanks,
Oliver

**Comment by RonnyWeiss** [comment]
Hello

I don't use material theme, but maybe you can fork it and build the plugin for mateiral theme?
