### ISSUE TITLE
Auto Refresh

### ISSUE THREAD

**Issue by emohdaziz** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#7]
Hi Ronny,

I'm just wondering how to make refresh automated after accept or decline.

Thanks,

**Comment by RonnyWeiss** [comment]
Hello

Good question but I already thought about that and my problem ist that the plug-in could not know when you accept or decline is finished. So you need to trigger the refresh by your own. Just checkout my sample app on page 2. Theres a refresh button where you can check the code how to do it. The sample app can be downloaded on https://ronnyweiss.app and it can be installed on https://apex.oracle.com or another APEX 20.1.

Hope this will help you:

you can set a static id in the plug-in attributes:

![grafik](https://user-images.githubusercontent.com/30749177/86042494-8846b100-ba47-11ea-9b8d-dd3cf5339559.png)

Then after trigger accept or decline you fire a refresh on this id:

![grafik](https://user-images.githubusercontent.com/30749177/86042588-aad8ca00-ba47-11ea-8976-052fbe23d301.png)

What do you call on accept or decline?

Kind regards

Ronny

**Comment by Ennio71** [comment]
As written in #5 i suggest this methods:
**If you need to trigger an action and then refresh notifications**
- Put an hidden item in your page 0 ( or where you need). For me the name is `P0_MESSAGE_ID` and contains the key for the record to update
- On the item create a dynamic action for the event `change` and type `Execute PL/SQL code`
- Add to the DA a `TRUE action` -> type `Refresh` -> Selection Type: `jQuery Selector`, jQuery Selector: `"the static ID of the notification region"`
- In the initialization of the plugin put this in the SELECT (example for DECLINE clicked)): `'javascript:apex.item("P0_MESSAGE_ID").setValue('|| your_value ||');'AS NOTE_DECLINE`

In this way the item is changed so the DA triggers and, after the execution of the PL/SQL, a region refresh is executed

**If you need only refresh notifications**
- In the initialization of the plugin put this in the SELECT (example for DECLINE clicked)): `'javascript:apex.region("the static ID of the notification region").refresh();'AS NOTE_DECLINE`

In this way only a region refresh is executed

Hope this helps

**Comment by RonnyWeiss** [comment]
So now it works for you?

**Comment by fecola** [comment]
Hi Ronny, nice plugin, thanks....but i'm a dificulty.

I have a table that I restore the notifications messages, and a column call READ = 'S' or 'N'. That to notifications don't appear again.

My query from DA is
```
SELECT /* sets the icon of the list item  (fa-exclamation-triangle) */
    nvl(icon,'fa-exclamation-triangle') AS NOTE_ICON, 
    /* sets the color of the list icon */
    'rgb(192,0,15)' AS NOTE_ICON_COLOR, 
    /* sets the title of the list item (html possible) */
    ASSUNTO AS NOTE_HEADER,
    /* sets the text of the list item (html possible */
    --'My first Notification ' AS NOTE_TEXT, 
    MSG_NOT AS NOTE_TEXT, 
    /* set the link when click on list item */
    --'javascript:alert("Click on Notification Entry");void(0);' AS NOTE_LINK, 
    /* sets the color of the left box shadow */
    'rgb(192,0,15)' AS NOTE_COLOR,
    /* Link or js that is executed when press accept link (if left or null not accept is shown */ 
    'javascript:apex.server.process("ATUALIZA_NOTIFICACAO", {X01: ' || ID_NOTIFICATIONS_MSG || ' }, 
							{
							refreshObject(getElementById("notification-menu_toggleNote")),
							error: function( jqXHR, textStatus, errorThrown ) {}
							}
    );' AS NOTE_ACCEPT
    /* Link or js that is executed when press decline link (if left or null not decline is shown */ 
--    'javascript:alert("Declined");void(0);' AS NOTE_DECLINE,
    /* When enable Browser Notifications in ConfigJSON then you can select which notifications should not be fire browser not. */
  --  0 AS NO_BROWSER_NOTIFICATION
FROM
    NOTIFICATIONS_MSG
WHERE
    LIDA = 'N' AND
    ID_MARCAS_DEST = :GLOBAL_ID_MARCA_LOGADA;
```
![Sem título](https://user-images.githubusercontent.com/31574045/87228972-01fd6980-c37b-11ea-819f-f3794f25f127.png)


But when click NOTE_ACCEPT, I have an error at my console:
"Uncaught SyntaxError: Unexpected token '(' "
``
![image](https://user-images.githubusercontent.com/31574045/87228994-13df0c80-c37b-11ea-82c0-be7500dd30eb.png)

You may help me woth that?

**Comment by RonnyWeiss** [comment]
Yes but this bug is made by you :-)

You can not work in link with " because they where escaped so you have the following link:

apex.server.process(&quot;ATUALIZA_NOTIFICACAO&quot;, {X01: 2 }, 
							{
							refreshObject(getElementById(&quot;notification-menu_toggleNote&quot;)),
							error: function( jqXHR, textStatus, errorThrown ) {}
							}
    );

and this is no valid js code. A tip would be to fire just a trigger e.g. $('body').trigger('decline', 'ID_NOTIFICATION_MSG'); and make a dynamic action that is listening to this event and fires the apex.server.process or other code. Hope this will help you.

Kind regards

Ronny

**Comment by fecola** [comment]
Hi Ronny, thanks for replying.

I am aware that I am to blame for the mistake kkk ... but I wanted to innovate and I was in difficulty.
This advanced part of APEX, I am not very good, I have difficulties with JS. I didn't quite understand your guidance, sorry.
Can you help me in a little more detailed and clear with a possible solution to my problem?
I can give you my email if you prefer.
Thank you

**Comment by RonnyWeiss** [comment]
Hello

No problem:

For links please use:

javascript:apex.item('your_helper_apex_page_item').setValue(ID_NOTIFICATION_MSG);$( 'body').trigger( "dosomething");void(0);

Then you create a Dynamic action with:

![grafik](https://user-images.githubusercontent.com/30749177/87543398-fbd1fa80-c6a4-11ea-9f7c-fd758c91d5b1.png)

and then you can fire what you want in this dynamic action e.g. pl/sql code that reads the value from the item.

Hope this helps.

Kind regards

Ronny

**Comment by fecola** [comment]
Ronny, I almost did it.
I created a shared components> application item called GLOBAL_ID_NOTIFICACAO
My query was like this, it was how I managed to save it, otherwise I had an error:

![image](https://user-images.githubusercontent.com/31574045/87568486-19e72d00-c69c-11ea-9aa0-72788fe63649.png)

The dynamic action he asked to create, looked like this:
![image](https://user-images.githubusercontent.com/31574045/87568544-33887480-c69c-11ea-80fd-ad847ce21ea6.png)


But it turns out that my item GLOBAL_ID_NOTIFICACAO, is not receiving the value.

**Comment by RonnyWeiss** [comment]
you also have a " in your link you need to use ' and not " in links ;-) so please try again :-)

**Comment by fecola** [comment]
I'm trying all possibilities kkk

'javascript:apex.item(' || :GLOBAL_ID_NOTIFICACAO || ').setValue(' || ID_NOTIFICATIONS_MSG || ');$("body").trigger("dosomething"); void(0);' AS NOTE_ACCEPT
the item GLOBAL_ID_NOTIFICATION not is recogonized
![image](https://user-images.githubusercontent.com/31574045/87789314-38246880-c815-11ea-9465-1cffc90478c1.png)


    'javascript:apex.item(' || :GLOBAL_ID_NOTIFICACAO || ').setValue(' || ID_NOTIFICATIONS_MSG || ');$('body').trigger("dosomething"); void(0);' AS NOTE_ACCEPT
this way, not is vlaid code
![image](https://user-images.githubusercontent.com/31574045/87789377-54280a00-c815-11ea-95ff-dc07135e6738.png)

**Comment by Ennio71** [comment]
I suggest you read here [https://docs.oracle.com/cd/E71588_01/AEAPI/apex-item.htm#GUID-4ED30237-2C25-4CEC-9C20-FF325389E094](url) and not go on trial and error.
Best regards
Ennio

**Comment by Ennio71** [comment]
Take a look at [the documentation](https://docs.oracle.com/cd/E71588_01/AEAPI/apex-item.htm#AEAPI29496) don't go with trial and errors.
Or read [here](https://github.com/RonnyWeiss/Apex-Notification-Menu-for-NavBar/issues/7#issuecomment-652246490)

**Comment by fecola** [comment]
Uuhhuuuuu

Thanks so much @Ennio71 and @RonnyWeiss ... you are the bests.
I got do and works perfectly.

This is how it works:
'javascript:apex.item("P0_ID_NOTIFICACAO").setValue(' || ID_NOTIFICATIONS_MSG || ');$("body").trigger("dosomething");apex.region("notification-menu").refresh();' AS NOTE_ACCEPT

I'm so happy now, thanks to you

**Comment by fecola** [comment]
Uuhhuuuuu

Thanks so much @Ennio71 and @RonnyWeiss ... you are the bests.
I got do and works perfectly.

This is how it works:
'javascript:apex.item("P0_ID_NOTIFICACAO").setValue(' || ID_NOTIFICATIONS_MSG || ');$("body").trigger("dosomething");apex.region("notification-menu").refresh();' AS NOTE_ACCEPT

I'm so happy now, thanks to you

**Comment by fecola** [comment]
Uuhhuuuuu

Thanks so much @Ennio71 and @RonnyWeiss ... you are the bests.
I got do and works perfectly.

This is how it works:
'javascript:apex.item("P0_ID_NOTIFICACAO").setValue(' || ID_NOTIFICATIONS_MSG || ');$("body").trigger("dosomething");javascript:apex.region("notification-menu").refresh();' AS NOTE_ACCEPT

I'm so happy now, thanks to you

**Comment by Ennio71** [comment]
I'm happy you have solved, but I've the doubt that you have only copy and pasted the code without understanding the meaning. But if it works, works :)
Cheers

**Comment by fecola** [comment]
On the contrary @Ennio71  ... the link to the documentation you sent, made me clarify and locate my error. And the link to an answer here on this forum also helped me completely to refresh the region.
I knew what the query was doing, but I didn't know how it worked. And reading the documentation, I saw that I need to specify a page item, on the page where I am informing this code. I was using an "application item", so I couldn't find it to pass the value on.
In addition to previous errors reported by @RonnyWeiss .

You were indispensable for my problem, I am very grateful.

**Comment by Ennio71** [comment]
I didn't mean to offend you, but  if you run the pl/sql code in the on-change DA of the item and then refresh the region always using the on-change DA of the item in the javascript you only need 
`'javascript:apex.item("P0_ID_NOTIFICACAO").setValue(' || ID_NOTIFICATIONS_MSG || ');`
This only to keep te code clean.
Cheers

**Comment by fecola** [comment]
No no man, rest assured that I was not offended in any way.
I like it when they question me, because it instigates me to investigate, analyze and be sure of what is happening. It is very easy to program by copying and pasting code, without knowing how and why it works.

I got your idea.
A good practice is to focus on resources at the client level and not at the server level, is that it?

**Comment by Ennio71** [comment]
Good question but I don't have the right response.
When I code, I try to follow the KISS principle thinking at the programmer that comes after me in mainteining the code ;-)
That's it 
Cheers

**Comment by RonnyWeiss** [comment]
@Ennio71 is true you could also Listen to change Event of item and put rest of the Code in dynamic Action thisv would be best maintainable 😎
