### ISSUE TITLE
Error installing?

### ISSUE THREAD

**Issue by gomanuke** [RonnyWeiss/Apex-Notification-Menu-for-NavBar#8]
Would You clarify, how i can figure out an error's reason?
After realizing Your installing instruction it leads to short page with the followin data:

Error installing plug-in.
ORA-01403: no data found
 UserADMIN  WORKSPACENAME  en
Copyright © 1999, 2019, Oracle. All rights reserved.
Application Express 19.2.0.00.18

**Comment by RonnyWeiss** [comment]
Did you check my Videos how to install and use my plugins on ronnyweiss.app?

**Comment by gomanuke** [comment]
It's shame to say, but it was crazy 7zip that iincorrectly unzipped archive. Unbelievable! Let's close the ticket.

**Comment by RonnyWeiss** [comment]
No problem
